import './globals.css';
import { Providers } from './providers';
import ShowNav from './ShowNav';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ShowNav>{children}</ShowNav>
        </Providers>
      </body>
    </html>
  )
}
