name: Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
      - name: Run API integration tests
        run: npm run test:api
      - name: Generate coverage badge
        run: |
          npm install -g coverage-badges-cli
          coverage-badges
      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage-badge.svg
          if-no-files-found: error

      - name: Update README with coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update coverage badge"
          file_pattern: |
            README.md
            coverage-badge.svg
          branch: main

# Instructions:
# 1. Create a gist on GitHub to store the badge JSON (empty file, e.g. coverage-badge.json).
# 2. Add the GIST_ID (the gist hash) and GIST_TOKEN (a GitHub token with gist scope) as repository secrets.
# 3. Update the badge URL in README.md to point to your gist. 